# Generated by Django 4.2 on 2024-06-08 18:50

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('specialization', models.CharField(max_length=255)),
                ('yearsExperiance', models.SmallIntegerField(default=0)),
                ('specialization_info', models.TextField()),
                ('displayName', models.BooleanField(default=True)),
                ('services', models.TextField()),
                ('workExperienseComapnies', models.TextField()),
                ('qualifications', models.TextField()),
                ('extraInfo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cerificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to=app.models.handle_upload_files)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='app.expert')),
            ],
        ),
    ]
