# Generated by Django 4.2 on 2024-06-13 18:40

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('general_specialization', models.CharField(max_length=255, verbose_name='التخصص العام')),
                ('sum_experience_years', models.SmallIntegerField(default=0, verbose_name='مجموع سنوات الخبرة العملية')),
                ('details_specialization_info', models.TextField(verbose_name='تخصص دقيق')),
                ('display_name_type', models.CharField(choices=[('YES', 'نعم'), ('NO', 'لا')], default='نعم', max_length=3, verbose_name='هل ترغب بعرض اسمك و صورتك')),
                ('services', models.TextField(verbose_name='الخدمات التي يمكن تقديمها و الاستشارات')),
                ('work_experiense_comapnies', models.TextField(verbose_name='الجهات التي عملتم معها')),
                ('study_qualifications', models.TextField(verbose_name='الجهات التي حصلتم منها على شهادة اكاديمية')),
                ('heigh_special_companies', models.TextField(verbose_name='الجهات التي لديكم فيها عضوية مجلس ادارة او استشارة او تعاون')),
                ('extraInfo', models.TextField(blank=True, null=True, verbose_name='اقتراحات او تفاصيل او معلومات هامة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الارسال')),
            ],
            options={
                'verbose_name_plural': 'طلبات الانضمام كخبير',
            },
        ),
        migrations.CreateModel(
            name='Vocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='الاسم الاول')),
                ('last_name', models.CharField(max_length=255, verbose_name='الاسم الاخير')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الالكتروني')),
                ('phone', models.CharField(max_length=25, verbose_name='رقم الهاتف')),
                ('message', models.TextField(verbose_name='تفاصيل الاستشارة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الارسال')),
            ],
            options={
                'verbose_name_plural': 'طلبات الاستشارة',
            },
        ),
        migrations.CreateModel(
            name='Cerificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to=app.models.handle_upload_files, verbose_name='الرخصة')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='app.expert')),
            ],
            options={
                'verbose_name_plural': 'الرخص المهنية',
            },
        ),
    ]
